### ISSUE TITLE
t190095

### ISSUE THREAD

**Issue by t190095** [nc2020/2#3]
![3F9427A5-2ECE-4737-8FFD-A674A39FAA4A](https://user-images.githubusercontent.com/63433887/79523348-eabf2080-8098-11ea-8775-1d5ef7850fd8.jpeg)
![636C044B-68AC-40F1-B6B6-3FB5B68A6808](https://user-images.githubusercontent.com/63433887/79523355-ec88e400-8098-11ea-9f0a-c5b6a344f9e6.jpeg)
3 \times 15=45

**Comment by junta-m** [comment]
ここではなく、https://github.com/nc2020/2-t190095 の方に提出してください。
